'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強類型資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CookingMaster.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強類型資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property ch1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ch1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property ch2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ch2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property coffee() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("coffee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property DishList1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DishList1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property DishList2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DishList2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property DishList3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DishList3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property ed1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ed1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property ed2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ed2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property ed3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ed3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property fishsushi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fishsushi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property hamberger2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("hamberger2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property japan() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("japan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property namaita() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("namaita", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property plate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property rice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property voice_mute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("voice_mute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property voice_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("voice_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 主畫面背景圖() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("主畫面背景圖", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 出餐口() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("出餐口", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 出餐口_完整漢堡1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("出餐口_完整漢堡1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 出餐口_完整漢堡2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("出餐口_完整漢堡2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 垃圾桶() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("垃圾桶", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 垃圾桶_蛋() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("垃圾桶_蛋", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 完整漢堡1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("完整漢堡1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 完整漢堡2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("完整漢堡2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 巧克力() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("巧克力", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 巧克力蛋糕() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("巧克力蛋糕", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 巧克力麵團() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("巧克力麵團", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 日式餐廳背景圖() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("日式餐廳背景圖", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 桌子() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桌子", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 桌子_攪拌機_巧克力_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桌子_攪拌機_巧克力_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 桌子_攪拌機_空_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桌子_攪拌機_空_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 桌子_攪拌機_草莓_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桌子_攪拌機_草莓_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 桌子_攪拌機_蜂蜜_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桌子_攪拌機_蜂蜜_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 桌子_烤箱_有蛋糕_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桌子_烤箱_有蛋糕_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 桌子_烤箱_空_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桌子_烤箱_空_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 桌子_砧板() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桌子_砧板", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 桌子_蛋() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桌子_蛋", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 桌子_鍋架_平底鍋() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桌子_鍋架_平底鍋", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 桌子_鍋架_平底鍋_漢堡肉() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桌子_鍋架_平底鍋_漢堡肉", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 桌子_飯鍋() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桌子_飯鍋", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 洗碗槽() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("洗碗槽", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 洗碗槽_髒盤子() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("洗碗槽_髒盤子", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 海苔() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("海苔", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 漢堡肉() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("漢堡肉", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 煎() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("煎", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 生漢堡肉() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("生漢堡肉", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 生菜() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("生菜", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 生菜_前_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("生菜_前_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 番茄() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("番茄", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 番茄切片() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("番茄切片", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 盤子() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("盤子", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 砧板_生菜() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("砧板_生菜", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 砧板_番茄() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("砧板_番茄", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 砧板_蝦() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("砧板_蝦", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 砧板_魚() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("砧板_魚", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 米飯() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("米飯", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 結束遊戲() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("結束遊戲", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 美式餐廳背景圖() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("美式餐廳背景圖", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 草莓() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("草莓", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 草莓蛋糕() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("草莓蛋糕", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 草莓麵團() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("草莓麵團", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 蛋糕店背景圖() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("蛋糕店背景圖", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 蜂蜜() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("蜂蜜", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 蜂蜜蛋糕() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("蜂蜜蛋糕", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 蜂蜜麵團() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("蜂蜜麵團", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 蝦仁() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("蝦仁", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 蝦前() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("蝦前", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 蝦後() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("蝦後", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 訂單完整漢堡1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("訂單完整漢堡1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 訂單完整漢堡2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("訂單完整漢堡2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 訂單巧克力蛋糕() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("訂單巧克力蛋糕", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 訂單草莓蛋糕() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("訂單草莓蛋糕", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 訂單蜂蜜蛋糕() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("訂單蜂蜜蛋糕", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 訂單豆皮壽司() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("訂單豆皮壽司", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 訂單鮮蝦壽司() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("訂單鮮蝦壽司", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 訂單鮮魚壽司() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("訂單鮮魚壽司", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 豆皮() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("豆皮", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 豆皮壽司() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("豆皮壽司", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 豆皮壽司1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("豆皮壽司1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 起司() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("起司", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 開始遊戲() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("開始遊戲", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 雞蛋() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("雞蛋", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_巧克力() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_巧克力", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_海苔() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_海苔", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_漢堡肉() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_漢堡肉", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_生漢堡肉() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_生漢堡肉", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_生菜() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_生菜", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_番茄() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_番茄", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_米飯() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_米飯", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_草莓() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_草莓", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_蜂蜜() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_蜂蜜", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_蝦() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_蝦", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_豆皮() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_豆皮", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_起司() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_起司", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_雞蛋() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_雞蛋", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_魚() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_魚", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_麵包() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_麵包", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 食材箱_麵粉() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("食材箱_麵粉", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 髒盤子() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("髒盤子", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 魚() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("魚", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 魚切後() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("魚切後", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 鮮蝦壽司() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("鮮蝦壽司", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 鮮魚壽司() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("鮮魚壽司", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 麵包() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("麵包", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 麵粉() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("麵粉", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
